# Generated by Django 5.2.17 on 2026-10-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffresApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='statut',
            field=models.CharField(choices=[('proposee', 'proposee'), ('acceptee', 'acceptee'), ('refusee', 'refusee'), ('retiree', 'retiree')], default='proposee', max_length=20),
        ),
    ]
