# Generated by Django 5.2.17 on 2026-10-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiculesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('camionnette', 'camionnette'), ('fourgon', 'fourgon'), ('camion_porteur', 'camion_porteur'), ('semi-remorque', 'semi-remorque')], max_length=50),
        ),
    ]
