# Generated by Django 5.2.17 on 2026-10-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='type_entreprise',
            field=models.CharField(choices=[('chargeur', 'chargeur'), ('transporteur', 'transporteur')], max_length=15),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('chargeur', 'chargeur'), ('transporteur', 'transporteur'), ('admin', 'admin')], default='chargeur', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
