# Generated by Django 5.2.17 on 2026-10-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpeditionsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='reference',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='statut',
            field=models.CharField(choices=[('publiee', 'publiee'), ('attribuee', 'attribuee'), ('en_cours', 'en_cours'), ('livree', 'livree'), ('annulee', 'annulee')], default='publiee', max_length=20),
        ),
    ]
